title: 'Dream to Control:<br>Learning Behaviors by Latent Imagination'
description:
- Danijar Hafner, Timothy Lillicrap, Jimmy Ba, Mohammad Norouzi
- ICLR 2020 Spotlight
buttons:
  Research paper: 'https://arxiv.org/pdf/1912.01603.pdf'
  Source code: 'https://github.com/danijar/dreamer'
