title: 'Dream to Control:<br>Learning Behaviors by Latent Imagination'
description:
- Danijar Hafner, Timothy Lillicrap, Jimmy Ba, Mohammad Norouzi
- Google Brain, University of Toronto, DeepMind
- ICLR 2020 Spotlight
buttons:
  Blog post: 'https://ai.googleblog.com/2020/03/introducing-dreamer-scalable.html'
  Paper PDF: 'https://arxiv.org/pdf/1912.01603.pdf'
  Source code: 'https://github.com/danijar/dreamer'
